name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-laravel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: "cd /home/ubuntu/devops && ./deploy.sh"
